version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: "redis:7"
    ports:
      - "6379:6379"
