# Generated by Django 5.0 on 2024-01-01 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_chat', '0002_customuser_otp_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contacts',
            field=models.ManyToManyField(related_name='user_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
