# Generated by Django 5.0 on 2024-01-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_chat', '0003_remove_contacts_contact_remove_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
